# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rozklad', '0002_zupynka'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Route Bus Name',
                'verbose_name_plural': 'Route Bus Names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('zupynks', models.ManyToManyField(to='rozklad.Zupynka', verbose_name='Zupynka Names')),
            ],
            options={
                'verbose_name': 'Village Name',
                'verbose_name_plural': 'Village Names',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='routebus',
            name='across_village',
            field=models.ManyToManyField(related_name='across_village', to='rozklad.Village', verbose_name='From village'),
        ),
        migrations.AddField(
            model_name='routebus',
            name='from_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_village', to='rozklad.Village', verbose_name='From village'),
        ),
        migrations.AddField(
            model_name='routebus',
            name='to_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_village', to='rozklad.Village', verbose_name='From village'),
        ),
    ]
